create sequence address_seq start with 1 increment by 50;
create sequence chart_item_seq start with 1 increment by 50;
create sequence orders_seq start with 1 increment by 50;
create sequence product_seq start with 1 increment by 50;
create table address (zip_code integer, id bigint not null, city varchar(255), house_number varchar(255), street varchar(255), primary key (id));
create table chart_item (amount integer not null, id bigint not null, order_id bigint, product_id bigint, primary key (id));
create table orders (address_id bigint unique, id bigint not null, shipment_id bigint not null, name varchar(255), status varchar(255) check (status in ('PENDING','CONFIRMED','DECLINED','SHIPMENT_FAILED','DELIVERED')), primary key (id));
create table product (price integer not null, id bigint not null, name varchar(255), primary key (id));
alter table if exists chart_item add constraint FKgsilrybyxqhatdo537k58h2pq foreign key (order_id) references orders;
alter table if exists chart_item add constraint FKbf2iw96cddynj4tuu9wsd4g8l foreign key (product_id) references product;
alter table if exists orders add constraint FKf5464gxwc32ongdvka2rtvw96 foreign key (address_id) references address;
create sequence address_seq start with 1 increment by 50;
create sequence chart_item_seq start with 1 increment by 50;
create sequence orders_seq start with 1 increment by 50;
create sequence product_seq start with 1 increment by 50;
create table address (zip_code integer, id bigint not null, city varchar(255), house_number varchar(255), street varchar(255), primary key (id));
create table chart_item (amount integer not null, id bigint not null, order_id bigint, product_id bigint, primary key (id));
create table orders (address_id bigint unique, id bigint not null, shipment_id bigint not null, name varchar(255), status varchar(255) check (status in ('PENDING','CONFIRMED','DECLINED','SHIPMENT_FAILED','DELIVERED')), primary key (id));
create table product (price integer not null, id bigint not null, name varchar(255), primary key (id));
alter table if exists chart_item add constraint FKgsilrybyxqhatdo537k58h2pq foreign key (order_id) references orders;
alter table if exists chart_item add constraint FKbf2iw96cddynj4tuu9wsd4g8l foreign key (product_id) references product;
alter table if exists orders add constraint FKf5464gxwc32ongdvka2rtvw96 foreign key (address_id) references address;
create sequence address_seq start with 1 increment by 50;
create sequence chart_item_seq start with 1 increment by 50;
create sequence orders_seq start with 1 increment by 50;
create sequence product_seq start with 1 increment by 50;
create table address (zip_code integer, id bigint not null, city varchar(255), house_number varchar(255), street varchar(255), primary key (id));
create table chart_item (amount integer not null, id bigint not null, order_id bigint, product_id bigint, primary key (id));
create table orders (address_id bigint unique, id bigint not null, shipment_id bigint not null, name varchar(255), status varchar(255) check (status in ('PENDING','CONFIRMED','DECLINED','SHIPMENT_FAILED','DELIVERED')), primary key (id));
create table product (price integer not null, id bigint not null, name varchar(255), primary key (id));
alter table if exists chart_item add constraint FKgsilrybyxqhatdo537k58h2pq foreign key (order_id) references orders;
alter table if exists chart_item add constraint FKbf2iw96cddynj4tuu9wsd4g8l foreign key (product_id) references product;
alter table if exists orders add constraint FKf5464gxwc32ongdvka2rtvw96 foreign key (address_id) references address;
create sequence address_seq start with 1 increment by 50;
create sequence chart_item_seq start with 1 increment by 50;
create sequence orders_seq start with 1 increment by 50;
create sequence product_seq start with 1 increment by 50;
create table address (zip_code integer, id bigint not null, city varchar(255), house_number varchar(255), street varchar(255), primary key (id));
create table chart_item (amount integer not null, id bigint not null, order_id bigint, product_id bigint, primary key (id));
create table orders (address_id bigint unique, id bigint not null, shipment_id bigint not null, name varchar(255), status varchar(255) check (status in ('PENDING','CONFIRMED','DECLINED','SHIPMENT_FAILED','DELIVERED')), primary key (id));
create table product (price integer not null, id bigint not null, name varchar(255), primary key (id));
alter table if exists chart_item add constraint FKgsilrybyxqhatdo537k58h2pq foreign key (order_id) references orders;
alter table if exists chart_item add constraint FKbf2iw96cddynj4tuu9wsd4g8l foreign key (product_id) references product;
alter table if exists orders add constraint FKf5464gxwc32ongdvka2rtvw96 foreign key (address_id) references address;
create sequence address_seq start with 1 increment by 50;
create sequence chart_item_seq start with 1 increment by 50;
create sequence orders_seq start with 1 increment by 50;
create sequence product_seq start with 1 increment by 50;
create table address (zip_code integer, id bigint not null, city varchar(255), house_number varchar(255), street varchar(255), primary key (id));
create table chart_item (amount integer not null, id bigint not null, order_id bigint, product_id bigint, primary key (id));
create table orders (address_id bigint unique, id bigint not null, shipment_id bigint not null, name varchar(255), status varchar(255) check (status in ('PENDING','CONFIRMED','DECLINED','SHIPMENT_FAILED','DELIVERED')), primary key (id));
create table product (price integer not null, id bigint not null, name varchar(255), primary key (id));
alter table if exists chart_item add constraint FKgsilrybyxqhatdo537k58h2pq foreign key (order_id) references orders;
alter table if exists chart_item add constraint FKbf2iw96cddynj4tuu9wsd4g8l foreign key (product_id) references product;
alter table if exists orders add constraint FKf5464gxwc32ongdvka2rtvw96 foreign key (address_id) references address;
create sequence address_seq start with 1 increment by 50;
create sequence chart_item_seq start with 1 increment by 50;
create sequence orders_seq start with 1 increment by 50;
create sequence product_seq start with 1 increment by 50;
create table address (zip_code integer, id bigint not null, city varchar(255), house_number varchar(255), street varchar(255), primary key (id));
create table chart_item (amount integer not null, id bigint not null, order_id bigint, product_id bigint, primary key (id));
create table orders (address_id bigint unique, id bigint not null, shipment_id bigint not null, name varchar(255), status varchar(255) check (status in ('PENDING','CONFIRMED','DECLINED','SHIPMENT_FAILED','DELIVERED')), primary key (id));
create table product (price integer not null, id bigint not null, name varchar(255), primary key (id));
alter table if exists chart_item add constraint FKgsilrybyxqhatdo537k58h2pq foreign key (order_id) references orders;
alter table if exists chart_item add constraint FKbf2iw96cddynj4tuu9wsd4g8l foreign key (product_id) references product;
alter table if exists orders add constraint FKf5464gxwc32ongdvka2rtvw96 foreign key (address_id) references address;
create sequence address_seq start with 1 increment by 50;
create sequence chart_item_seq start with 1 increment by 50;
create sequence orders_seq start with 1 increment by 50;
create sequence product_seq start with 1 increment by 50;
create table address (zip_code integer, id bigint not null, city varchar(255), house_number varchar(255), street varchar(255), primary key (id));
create table chart_item (amount integer not null, id bigint not null, order_id bigint, product_id bigint, primary key (id));
create table orders (address_id bigint unique, id bigint not null, shipment_id bigint not null, name varchar(255), status varchar(255) check (status in ('PENDING','CONFIRMED','DECLINED','SHIPMENT_FAILED','DELIVERED')), primary key (id));
create table product (price integer not null, id bigint not null, name varchar(255), primary key (id));
alter table if exists chart_item add constraint FKgsilrybyxqhatdo537k58h2pq foreign key (order_id) references orders;
alter table if exists chart_item add constraint FKbf2iw96cddynj4tuu9wsd4g8l foreign key (product_id) references product;
alter table if exists orders add constraint FKf5464gxwc32ongdvka2rtvw96 foreign key (address_id) references address;
create sequence address_seq start with 1 increment by 50;
create sequence chart_item_seq start with 1 increment by 50;
create sequence orders_seq start with 1 increment by 50;
create sequence product_seq start with 1 increment by 50;
create table address (zip_code integer, id bigint not null, city varchar(255), house_number varchar(255), street varchar(255), primary key (id));
create table chart_item (amount integer not null, id bigint not null, order_id bigint, product_id bigint, primary key (id));
create table orders (address_id bigint unique, id bigint not null, shipment_id bigint not null, name varchar(255), status varchar(255) check (status in ('PENDING','CONFIRMED','DECLINED','SHIPMENT_FAILED','DELIVERED')), primary key (id));
create table product (price integer not null, id bigint not null, name varchar(255), primary key (id));
alter table if exists chart_item add constraint FKgsilrybyxqhatdo537k58h2pq foreign key (order_id) references orders;
alter table if exists chart_item add constraint FKbf2iw96cddynj4tuu9wsd4g8l foreign key (product_id) references product;
alter table if exists orders add constraint FKf5464gxwc32ongdvka2rtvw96 foreign key (address_id) references address;
create sequence address_seq start with 1 increment by 50;
create sequence chart_item_seq start with 1 increment by 50;
create sequence orders_seq start with 1 increment by 50;
create sequence product_seq start with 1 increment by 50;
create table address (zip_code integer, id bigint not null, city varchar(255), house_number varchar(255), street varchar(255), primary key (id));
create table chart_item (amount integer not null, id bigint not null, order_id bigint, product_id bigint, primary key (id));
create table orders (address_id bigint unique, id bigint not null, shipment_id bigint not null, name varchar(255), status varchar(255) check (status in ('PENDING','CONFIRMED','DECLINED','SHIPMENT_FAILED','DELIVERED')), primary key (id));
create table product (price integer not null, id bigint not null, name varchar(255), primary key (id));
alter table if exists chart_item add constraint FKgsilrybyxqhatdo537k58h2pq foreign key (order_id) references orders;
alter table if exists chart_item add constraint FKbf2iw96cddynj4tuu9wsd4g8l foreign key (product_id) references product;
alter table if exists orders add constraint FKf5464gxwc32ongdvka2rtvw96 foreign key (address_id) references address;
create sequence address_seq start with 1 increment by 50;
create sequence chart_item_seq start with 1 increment by 50;
create sequence orders_seq start with 1 increment by 50;
create sequence product_seq start with 1 increment by 50;
create table address (zip_code integer, id bigint not null, city varchar(255), house_number varchar(255), street varchar(255), primary key (id));
create table chart_item (amount integer not null, id bigint not null, order_id bigint, product_id bigint, primary key (id));
create table orders (address_id bigint unique, id bigint not null, shipment_id bigint not null, name varchar(255), status varchar(255) check (status in ('PENDING','CONFIRMED','DECLINED','SHIPMENT_FAILED','DELIVERED')), primary key (id));
create table product (price integer not null, id bigint not null, name varchar(255), primary key (id));
alter table if exists chart_item add constraint FKgsilrybyxqhatdo537k58h2pq foreign key (order_id) references orders;
alter table if exists chart_item add constraint FKbf2iw96cddynj4tuu9wsd4g8l foreign key (product_id) references product;
alter table if exists orders add constraint FKf5464gxwc32ongdvka2rtvw96 foreign key (address_id) references address;
create sequence address_seq start with 1 increment by 50;
create sequence chart_item_seq start with 1 increment by 50;
create sequence orders_seq start with 1 increment by 50;
create sequence product_seq start with 1 increment by 50;
create table address (zip_code integer, id bigint not null, city varchar(255), house_number varchar(255), street varchar(255), primary key (id));
create table chart_item (amount integer not null, id bigint not null, order_id bigint, product_id bigint, primary key (id));
create table orders (address_id bigint unique, id bigint not null, shipment_id bigint not null, name varchar(255), status varchar(255) check (status in ('PENDING','CONFIRMED','DECLINED','SHIPMENT_FAILED','DELIVERED')), primary key (id));
create table product (price integer not null, id bigint not null, name varchar(255), primary key (id));
alter table if exists chart_item add constraint FKgsilrybyxqhatdo537k58h2pq foreign key (order_id) references orders;
alter table if exists chart_item add constraint FKbf2iw96cddynj4tuu9wsd4g8l foreign key (product_id) references product;
alter table if exists orders add constraint FKf5464gxwc32ongdvka2rtvw96 foreign key (address_id) references address;
create sequence address_seq start with 1 increment by 50;
create sequence chart_item_seq start with 1 increment by 50;
create sequence orders_seq start with 1 increment by 50;
create sequence product_seq start with 1 increment by 50;
create table address (zip_code integer, id bigint not null, city varchar(255), house_number varchar(255), street varchar(255), primary key (id));
create table chart_item (amount integer not null, id bigint not null, order_id bigint, product_id bigint, primary key (id));
create table orders (address_id bigint unique, id bigint not null, shipment_id bigint not null, name varchar(255), status varchar(255) check (status in ('PENDING','CONFIRMED','DECLINED','SHIPMENT_FAILED','DELIVERED')), primary key (id));
create table product (price integer not null, id bigint not null, name varchar(255), primary key (id));
alter table if exists chart_item add constraint FKgsilrybyxqhatdo537k58h2pq foreign key (order_id) references orders;
alter table if exists chart_item add constraint FKbf2iw96cddynj4tuu9wsd4g8l foreign key (product_id) references product;
alter table if exists orders add constraint FKf5464gxwc32ongdvka2rtvw96 foreign key (address_id) references address;
create sequence address_seq start with 1 increment by 50;
create sequence chart_item_seq start with 1 increment by 50;
create sequence orders_seq start with 1 increment by 50;
create sequence product_seq start with 1 increment by 50;
create table address (zip_code integer, id bigint not null, city varchar(255), house_number varchar(255), street varchar(255), primary key (id));
create table chart_item (amount integer not null, id bigint not null, order_id bigint, product_id bigint, primary key (id));
create table orders (address_id bigint unique, id bigint not null, shipment_id bigint not null, name varchar(255), status varchar(255) check (status in ('PENDING','CONFIRMED','DECLINED','SHIPMENT_FAILED','DELIVERED')), primary key (id));
create table product (price integer not null, id bigint not null, name varchar(255), primary key (id));
alter table if exists chart_item add constraint FKgsilrybyxqhatdo537k58h2pq foreign key (order_id) references orders;
alter table if exists chart_item add constraint FKbf2iw96cddynj4tuu9wsd4g8l foreign key (product_id) references product;
alter table if exists orders add constraint FKf5464gxwc32ongdvka2rtvw96 foreign key (address_id) references address;
create sequence address_seq start with 1 increment by 50;
create sequence chart_item_seq start with 1 increment by 50;
create sequence orders_seq start with 1 increment by 50;
create sequence product_seq start with 1 increment by 50;
create table address (zip_code integer, id bigint not null, city varchar(255), house_number varchar(255), street varchar(255), primary key (id));
create table chart_item (amount integer not null, id bigint not null, order_id bigint, product_id bigint, primary key (id));
create table orders (address_id bigint unique, id bigint not null, shipment_id bigint not null, name varchar(255), status varchar(255) check (status in ('PENDING','CONFIRMED','DECLINED','SHIPMENT_FAILED','DELIVERED')), primary key (id));
create table product (price integer not null, id bigint not null, name varchar(255), primary key (id));
alter table if exists chart_item add constraint FKgsilrybyxqhatdo537k58h2pq foreign key (order_id) references orders;
alter table if exists chart_item add constraint FKbf2iw96cddynj4tuu9wsd4g8l foreign key (product_id) references product;
alter table if exists orders add constraint FKf5464gxwc32ongdvka2rtvw96 foreign key (address_id) references address;
create sequence address_seq start with 1 increment by 50;
create sequence chart_item_seq start with 1 increment by 50;
create sequence orders_seq start with 1 increment by 50;
create sequence product_seq start with 1 increment by 50;
create table address (zip_code integer, id bigint not null, city varchar(255), house_number varchar(255), street varchar(255), primary key (id));
create table chart_item (amount integer not null, id bigint not null, order_id bigint, product_id bigint, primary key (id));
create table orders (address_id bigint unique, id bigint not null, shipment_id bigint not null, name varchar(255), status varchar(255) check (status in ('PENDING','CONFIRMED','DECLINED','SHIPMENT_FAILED','DELIVERED')), primary key (id));
create table product (price integer not null, id bigint not null, name varchar(255), primary key (id));
alter table if exists chart_item add constraint FKgsilrybyxqhatdo537k58h2pq foreign key (order_id) references orders;
alter table if exists chart_item add constraint FKbf2iw96cddynj4tuu9wsd4g8l foreign key (product_id) references product;
alter table if exists orders add constraint FKf5464gxwc32ongdvka2rtvw96 foreign key (address_id) references address;
create sequence address_seq start with 1 increment by 50;
create sequence chart_item_seq start with 1 increment by 50;
create sequence orders_seq start with 1 increment by 50;
create sequence product_seq start with 1 increment by 50;
create table address (zip_code integer, id bigint not null, city varchar(255), house_number varchar(255), street varchar(255), primary key (id));
create table chart_item (amount integer not null, id bigint not null, order_id bigint, product_id bigint, primary key (id));
create table orders (address_id bigint unique, id bigint not null, shipment_id bigint not null, name varchar(255), status varchar(255) check (status in ('PENDING','CONFIRMED','DECLINED','SHIPMENT_FAILED','DELIVERED')), primary key (id));
create table product (price integer not null, id bigint not null, name varchar(255), primary key (id));
alter table if exists chart_item add constraint FKgsilrybyxqhatdo537k58h2pq foreign key (order_id) references orders;
alter table if exists chart_item add constraint FKbf2iw96cddynj4tuu9wsd4g8l foreign key (product_id) references product;
alter table if exists orders add constraint FKf5464gxwc32ongdvka2rtvw96 foreign key (address_id) references address;
create sequence address_seq start with 1 increment by 50;
create sequence chart_item_seq start with 1 increment by 50;
create sequence orders_seq start with 1 increment by 50;
create sequence product_seq start with 1 increment by 50;
create table address (zip_code integer, id bigint not null, city varchar(255), house_number varchar(255), street varchar(255), primary key (id));
create table chart_item (amount integer not null, id bigint not null, order_id bigint, product_id bigint, primary key (id));
create table orders (address_id bigint unique, id bigint not null, shipment_id bigint not null, name varchar(255), status varchar(255) check (status in ('PENDING','CONFIRMED','DECLINED','SHIPMENT_FAILED','DELIVERED')), primary key (id));
create table product (price integer not null, id bigint not null, name varchar(255), primary key (id));
alter table if exists chart_item add constraint FKgsilrybyxqhatdo537k58h2pq foreign key (order_id) references orders;
alter table if exists chart_item add constraint FKbf2iw96cddynj4tuu9wsd4g8l foreign key (product_id) references product;
alter table if exists orders add constraint FKf5464gxwc32ongdvka2rtvw96 foreign key (address_id) references address;
create sequence address_seq start with 1 increment by 50;
create sequence chart_item_seq start with 1 increment by 50;
create sequence orders_seq start with 1 increment by 50;
create sequence product_seq start with 1 increment by 50;
create table address (zip_code integer, id bigint not null, city varchar(255), house_number varchar(255), street varchar(255), primary key (id));
create table chart_item (amount integer not null, id bigint not null, order_id bigint, product_id bigint, primary key (id));
create table orders (address_id bigint unique, id bigint not null, shipment_id bigint not null, name varchar(255), status varchar(255) check (status in ('PENDING','CONFIRMED','DECLINED','SHIPMENT_FAILED','DELIVERED')), primary key (id));
create table product (price integer not null, id bigint not null, name varchar(255), primary key (id));
alter table if exists chart_item add constraint FKgsilrybyxqhatdo537k58h2pq foreign key (order_id) references orders;
alter table if exists chart_item add constraint FKbf2iw96cddynj4tuu9wsd4g8l foreign key (product_id) references product;
alter table if exists orders add constraint FKf5464gxwc32ongdvka2rtvw96 foreign key (address_id) references address;
create sequence address_seq start with 1 increment by 50;
create sequence chart_item_seq start with 1 increment by 50;
create sequence product_seq start with 1 increment by 50;
create sequence shop_order_seq start with 1 increment by 50;
create table address (zip_code integer, id bigint not null, city varchar(255), house_number varchar(255), street varchar(255), primary key (id));
create table chart_item (amount integer not null, id bigint not null, order_id bigint, product_id bigint, primary key (id));
create table product (price integer not null, id bigint not null, name varchar(255), primary key (id));
create table shop_order (address_id bigint unique, id bigint not null, shipment_id bigint not null, name varchar(255), status varchar(255) check (status in ('PENDING','CONFIRMED','DECLINED','SHIPMENT_FAILED','DELIVERED')), primary key (id));
alter table if exists chart_item add constraint FK49m9r5v3lsll1gyqu6t0pmai1 foreign key (order_id) references shop_order;
alter table if exists chart_item add constraint FKbf2iw96cddynj4tuu9wsd4g8l foreign key (product_id) references product;
alter table if exists shop_order add constraint FK7qvgu9j9j0webqibpbjggiq10 foreign key (address_id) references address;
create sequence address_seq start with 1 increment by 50;
create sequence chart_item_seq start with 1 increment by 50;
create sequence product_seq start with 1 increment by 50;
create sequence shop_order_seq start with 1 increment by 50;
create table address (zip_code integer, id bigint not null, city varchar(255), house_number varchar(255), street varchar(255), primary key (id));
create table chart_item (amount integer not null, id bigint not null, order_id bigint, product_id bigint, primary key (id));
create table product (price integer not null, id bigint not null, name varchar(255), primary key (id));
create table shop_order (address_id bigint unique, id bigint not null, shipment_id bigint not null, name varchar(255), status varchar(255) check (status in ('PENDING','CONFIRMED','DECLINED','SHIPMENT_FAILED','DELIVERED')), primary key (id));
alter table if exists chart_item add constraint FK49m9r5v3lsll1gyqu6t0pmai1 foreign key (order_id) references shop_order;
alter table if exists chart_item add constraint FKbf2iw96cddynj4tuu9wsd4g8l foreign key (product_id) references product;
alter table if exists shop_order add constraint FK7qvgu9j9j0webqibpbjggiq10 foreign key (address_id) references address;
create sequence address_seq start with 1 increment by 50;
create sequence chart_item_seq start with 1 increment by 50;
create sequence product_seq start with 1 increment by 50;
create sequence shop_order_seq start with 1 increment by 50;
create table address (zip_code integer, id bigint not null, city varchar(255), house_number varchar(255), street varchar(255), primary key (id));
create table chart_item (amount integer not null, id bigint not null, order_id bigint, product_id bigint, primary key (id));
create table product (price integer not null, id bigint not null, name varchar(255), primary key (id));
create table shop_order (address_id bigint unique, id bigint not null, shipment_id bigint not null, name varchar(255), status varchar(255) check (status in ('PENDING','CONFIRMED','DECLINED','SHIPMENT_FAILED','DELIVERED')), primary key (id));
alter table if exists chart_item add constraint FK49m9r5v3lsll1gyqu6t0pmai1 foreign key (order_id) references shop_order;
alter table if exists chart_item add constraint FKbf2iw96cddynj4tuu9wsd4g8l foreign key (product_id) references product;
alter table if exists shop_order add constraint FK7qvgu9j9j0webqibpbjggiq10 foreign key (address_id) references address;
create sequence address_seq start with 1 increment by 50;
create sequence chart_item_seq start with 1 increment by 50;
create sequence product_seq start with 1 increment by 50;
create sequence shop_order_seq start with 1 increment by 50;
create table address (zip_code integer, id bigint not null, city varchar(255), house_number varchar(255), street varchar(255), primary key (id));
create table chart_item (amount integer not null, id bigint not null, order_id bigint, product_id bigint, primary key (id));
create table product (price integer not null, id bigint not null, name varchar(255), primary key (id));
create table shop_order (address_id bigint unique, id bigint not null, shipment_id bigint not null, name varchar(255), status varchar(255) check (status in ('PENDING','CONFIRMED','DECLINED','SHIPMENT_FAILED','DELIVERED')), primary key (id));
alter table if exists chart_item add constraint FK49m9r5v3lsll1gyqu6t0pmai1 foreign key (order_id) references shop_order;
alter table if exists chart_item add constraint FKbf2iw96cddynj4tuu9wsd4g8l foreign key (product_id) references product;
alter table if exists shop_order add constraint FK7qvgu9j9j0webqibpbjggiq10 foreign key (address_id) references address;
create sequence category_seq start with 1 increment by 50;
create sequence product_seq start with 1 increment by 50;
create sequence revinfo_seq start with 1 increment by 50;
create table category (id bigint not null, name varchar(255), primary key (id));
create table category_aud (rev integer not null, revtype smallint, id bigint not null, name varchar(255), primary key (rev, id));
create table product (price integer not null, category_id bigint, id bigint not null, name varchar(255), primary key (id));
create table product_aud (price integer, rev integer not null, revtype smallint, category_id bigint, id bigint not null, name varchar(255), primary key (rev, id));
create table revinfo (rev integer not null, revtstmp bigint, primary key (rev));
alter table if exists category_aud add constraint FKc9m640crhsib2ws80um6xuk1w foreign key (rev) references revinfo;
alter table if exists product add constraint FK1mtsbur82frn64de7balymq9s foreign key (category_id) references category;
alter table if exists product_aud add constraint FK9vwllld6jlw5xys1ay911oh1x foreign key (rev) references revinfo;
create sequence category_seq start with 1 increment by 50;
create sequence product_seq start with 1 increment by 50;
create sequence revinfo_seq start with 1 increment by 50;
create table category (id bigint not null, name varchar(255), primary key (id));
create table category_aud (rev integer not null, revtype smallint, id bigint not null, name varchar(255), primary key (rev, id));
create table product (price integer not null, category_id bigint, id bigint not null, name varchar(255), primary key (id));
create table product_aud (price integer, rev integer not null, revtype smallint, category_id bigint, id bigint not null, name varchar(255), primary key (rev, id));
create table revinfo (rev integer not null, revtstmp bigint, primary key (rev));
alter table if exists category_aud add constraint FKc9m640crhsib2ws80um6xuk1w foreign key (rev) references revinfo;
alter table if exists product add constraint FK1mtsbur82frn64de7balymq9s foreign key (category_id) references category;
alter table if exists product_aud add constraint FK9vwllld6jlw5xys1ay911oh1x foreign key (rev) references revinfo;
create sequence category_seq start with 1 increment by 50;
create sequence product_seq start with 1 increment by 50;
create sequence revinfo_seq start with 1 increment by 50;
create table category (id bigint not null, name varchar(255), primary key (id));
create table category_aud (rev integer not null, revtype smallint, id bigint not null, name varchar(255), primary key (rev, id));
create table product (price integer not null, category_id bigint, id bigint not null, name varchar(255), primary key (id));
create table product_aud (price integer, rev integer not null, revtype smallint, category_id bigint, id bigint not null, name varchar(255), primary key (rev, id));
create table revinfo (rev integer not null, revtstmp bigint, primary key (rev));
alter table if exists category_aud add constraint FKc9m640crhsib2ws80um6xuk1w foreign key (rev) references revinfo;
alter table if exists product add constraint FK1mtsbur82frn64de7balymq9s foreign key (category_id) references category;
alter table if exists product_aud add constraint FK9vwllld6jlw5xys1ay911oh1x foreign key (rev) references revinfo;
create sequence category_seq start with 1 increment by 50;
create sequence product_seq start with 1 increment by 50;
create sequence revinfo_seq start with 1 increment by 50;
create table category (id bigint not null, name varchar(255), primary key (id));
create table category_aud (rev integer not null, revtype smallint, id bigint not null, name varchar(255), primary key (rev, id));
create table product (price integer not null, category_id bigint, id bigint not null, name varchar(255), primary key (id));
create table product_aud (price integer, rev integer not null, revtype smallint, category_id bigint, id bigint not null, name varchar(255), primary key (rev, id));
create table revinfo (rev integer not null, revtstmp bigint, primary key (rev));
alter table if exists category_aud add constraint FKc9m640crhsib2ws80um6xuk1w foreign key (rev) references revinfo;
alter table if exists product add constraint FK1mtsbur82frn64de7balymq9s foreign key (category_id) references category;
alter table if exists product_aud add constraint FK9vwllld6jlw5xys1ay911oh1x foreign key (rev) references revinfo;
create sequence category_seq start with 1 increment by 50;
create sequence product_seq start with 1 increment by 50;
create sequence revinfo_seq start with 1 increment by 50;
create table category (id bigint not null, name varchar(255), primary key (id));
create table category_aud (rev integer not null, revtype smallint, id bigint not null, name varchar(255), primary key (rev, id));
create table product (price integer not null, category_id bigint, id bigint not null, name varchar(255), primary key (id));
create table product_aud (price integer, rev integer not null, revtype smallint, category_id bigint, id bigint not null, name varchar(255), primary key (rev, id));
create table revinfo (rev integer not null, revtstmp bigint, primary key (rev));
alter table if exists category_aud add constraint FKc9m640crhsib2ws80um6xuk1w foreign key (rev) references revinfo;
alter table if exists product add constraint FK1mtsbur82frn64de7balymq9s foreign key (category_id) references category;
alter table if exists product_aud add constraint FK9vwllld6jlw5xys1ay911oh1x foreign key (rev) references revinfo;
create sequence category_seq start with 1 increment by 50;
create sequence product_seq start with 1 increment by 50;
create sequence revinfo_seq start with 1 increment by 50;
create table category (id bigint not null, name varchar(255), primary key (id));
create table category_aud (rev integer not null, revtype smallint, id bigint not null, name varchar(255), primary key (rev, id));
create table product (price integer not null, category_id bigint, id bigint not null, name varchar(255), primary key (id));
create table product_aud (price integer, rev integer not null, revtype smallint, category_id bigint, id bigint not null, name varchar(255), primary key (rev, id));
create table revinfo (rev integer not null, revtstmp bigint, primary key (rev));
alter table if exists category_aud add constraint FKc9m640crhsib2ws80um6xuk1w foreign key (rev) references revinfo;
alter table if exists product add constraint FK1mtsbur82frn64de7balymq9s foreign key (category_id) references category;
alter table if exists product_aud add constraint FK9vwllld6jlw5xys1ay911oh1x foreign key (rev) references revinfo;
