server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/

hu:
  webuni:
    tokenlib:
      keypaths:
        public: /Users/balaz/Cubix/tokens/public.pem

spring:
  cloud:
    gateway:
      routes:
        - id: order
          uri: lb://order
          predicates:
            - Path=/order/**
          filters:
            - RewritePath=/order(?<segment>/?.*), /api$\{segment}
        - id: catalog
          uri: lb://catalog
          predicates:
            - Path=/catalog/**
          filters:
            - RewritePath=/catalog(?<segment>/?.*), /api$\{segment}
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users(?<segment>/?.*), /api$\{segment}