server:
  port: 8085
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/

spring:
  datasource:
            url: jdbc:postgresql://localhost:5432/order
            username: postgres
            password: postgres

hu:
  webuni:
    tokenlib:
      keypaths:
        public: /Users/balaz/Cubix/tokens/public.pem